---
abstract: 'Subclass of Log::Dispatch::Email that sends e-mail using Sendmail'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.130880'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Email-Sendmail
no_index:
  directory:
    - t
    - inc
requires:
  Log::Dispatch: 0
  Sys::Hostname: 0
  Test::More: 0.82
  Test::NoWarnings: 0
  Test::Requires: 0
version: 0.02
