--- #YAML:1.0
name:               Log-Dispatch-Email-Sendmail
version:            0.01
abstract:           Subclass of Log::Dispatch::Email that sends e-mail using sendmail
author:
    - Nigel Horne <njh@bandsman.co.uk>
license:            GPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Dispatch:     0
    Sys::Hostname:     0
    Test::More:        0.82
    Test::NoWarnings:  0
    Test::Requires:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
